/**
 * Alpha Workspace ΓÇö Reporting SDK
 *
 * Operations:
 *   - report.generate          : build a ReportDto from an analysis (deterministic)
 *   - report.export.pdf        : render a ReportDto into a PDF artifact
 *   - report.export.json       : render a ReportDto into a summary JSON artifact
 *   - report.export.statistics : render an analysis into a statistics text artifact
 *
 * Reporting composes the shared PDF renderer from the Documents SDK (utility,
 * not an operation call). All outputs are deterministic (BZ-3..5).
 */
import { buildPdf } from '../documents/pdf'
import type {
  OperationContext,
  OperationDefinition,
  OperationRegistry,
} from '../../platform/registries/operation-registry'
import type { SpreadsheetAnalysis } from '../spreadsheet/analyze'
import { buildReport, reportToPdfLines, statisticsText, summaryJson, type ReportDto } from './report'

const VERSION = '1.0.0'
const SDK = 'reporting'

export function registerReportingSdk(registry: OperationRegistry): void {
  const generateOp: OperationDefinition = {
    id: 'report.generate',
    domain: 'reporting',
    capability: 'generate',
    sdkOwner: SDK,
    name: 'Generate Report',
    description: 'Builds a structured report with a deterministic summary.',
    version: VERSION,
    dependsOn: ['spreadsheet.analyze'],
    inputSchema: {
      type: 'object',
      properties: {
        analysis: { type: 'object' },
        sourceName: { type: 'string' },
      },
    },
    outputSchema: { type: 'object', properties: { report: { type: 'object' } } },
    permission: 'data.process',
    tags: ['reporting', 'report'],
    handler: async (_ctx: OperationContext, input: Record<string, unknown>) => {
      const analysis = input.analysis as SpreadsheetAnalysis | undefined
      const source = String(input.sourceName ?? 'spreadsheet.csv')
      if (!analysis) return { ok: false, data: {}, error: 'No analysis provided.' }
      const report: ReportDto = buildReport({
        title: `Spreadsheet Report ΓÇö ${source}`,
        source,
        analysis,
      })
      return { ok: true, data: { report } }
    },
  }

  const exportPdfOp: OperationDefinition = {
    id: 'report.export.pdf',
    domain: 'reporting',
    capability: 'export-pdf',
    sdkOwner: SDK,
    name: 'Export Report to PDF',
    description: 'Renders a report into a PDF artifact.',
    version: VERSION,
    dependsOn: ['report.generate'],
    inputSchema: {
      type: 'object',
      properties: {
        report: { type: 'object' },
        analysisArtifactId: { type: 'string' },
      },
    },
    outputSchema: {
      type: 'object',
      properties: {
        pdfArtifactId: { type: 'string' },
        pdfName: { type: 'string' },
        pdfSize: { type: 'number' },
      },
    },
    artifactContract: {
      produces: [{ type: 'pdf', format: 'pdf', mime: 'application/pdf' }],
      consumes: ['analysis'],
    },
    permission: 'artifact.create',
    tags: ['reporting', 'export', 'pdf'],
    handler: async (ctx: OperationContext, input: Record<string, unknown>) => {
      const report = input.report as ReportDto | undefined
      if (!report) return { ok: false, data: {}, error: 'No report provided.' }
      const bytes = buildPdf({
        title: report.title,
        subtitle: `Generated by Alpha One ┬╖ ${report.generatedAt}`,
        lines: reportToPdfLines(report),
      })
      const artifact = await ctx.artifacts.create({
        name: `${safeFileBase(report.source)}.pdf`,
        type: 'pdf',
        format: 'pdf',
        mime: 'application/pdf',
        bytes,
        producer: 'report.export.pdf',
        parentArtifactId: typeof input.analysisArtifactId === 'string' ? input.analysisArtifactId : null,
        workflowRunId: ctx.runId,
        taskId: ctx.taskId,
        meta: { reportTitle: report.title, source: report.source },
      })
      return {
        ok: true,
        data: { pdfArtifactId: artifact.id, pdfName: artifact.name, pdfSize: artifact.size },
        artifactIds: [artifact.id],
      }
    },
  }

  const exportJsonOp: OperationDefinition = {
    id: 'report.export.json',
    domain: 'reporting',
    capability: 'export-json',
    sdkOwner: SDK,
    name: 'Export Summary JSON',
    description: 'Renders a report into a deterministic summary JSON artifact.',
    version: VERSION,
    dependsOn: ['report.generate'],
    inputSchema: {
      type: 'object',
      properties: {
        report: { type: 'object' },
        analysisArtifactId: { type: 'string' },
      },
    },
    outputSchema: {
      type: 'object',
      properties: {
        jsonArtifactId: { type: 'string' },
        jsonName: { type: 'string' },
        jsonSize: { type: 'number' },
      },
    },
    artifactContract: {
      produces: [{ type: 'summary', format: 'json', mime: 'application/json' }],
      consumes: ['analysis'],
    },
    permission: 'artifact.create',
    tags: ['reporting', 'export', 'json', 'summary'],
    handler: async (ctx: OperationContext, input: Record<string, unknown>) => {
      const report = input.report as ReportDto | undefined
      if (!report) return { ok: false, data: {}, error: 'No report provided.' }
      const payload = summaryJson(report)
      const artifact = await ctx.artifacts.create({
        name: `${safeFileBase(report.source)}-summary.json`,
        type: 'summary',
        format: 'json',
        mime: 'application/json',
        bytes: new TextEncoder().encode(JSON.stringify(payload, null, 2)),
        producer: 'report.export.json',
        parentArtifactId: typeof input.analysisArtifactId === 'string' ? input.analysisArtifactId : null,
        workflowRunId: ctx.runId,
        taskId: ctx.taskId,
        meta: { reportTitle: report.title, source: report.source },
      })
      return {
        ok: true,
        data: { jsonArtifactId: artifact.id, jsonName: artifact.name, jsonSize: artifact.size },
        artifactIds: [artifact.id],
      }
    },
  }

  const exportStatisticsOp: OperationDefinition = {
    id: 'report.export.statistics',
    domain: 'reporting',
    capability: 'export-statistics',
    sdkOwner: SDK,
    name: 'Export Statistics Report',
    description: 'Renders an analysis into a full statistics text artifact.',
    version: VERSION,
    dependsOn: ['report.generate'],
    inputSchema: {
      type: 'object',
      properties: {
        analysis: { type: 'object' },
        report: { type: 'object' },
        analysisArtifactId: { type: 'string' },
      },
    },
    outputSchema: {
      type: 'object',
      properties: {
        statisticsArtifactId: { type: 'string' },
        statisticsName: { type: 'string' },
        statisticsSize: { type: 'number' },
      },
    },
    artifactContract: {
      produces: [{ type: 'statistics', format: 'txt', mime: 'text/plain' }],
      consumes: ['analysis'],
    },
    permission: 'artifact.create',
    tags: ['reporting', 'export', 'statistics'],
    handler: async (ctx: OperationContext, input: Record<string, unknown>) => {
      const analysis = input.analysis as SpreadsheetAnalysis | undefined
      const report = input.report as ReportDto | undefined
      if (!analysis || !report) return { ok: false, data: {}, error: 'Analysis and report are required.' }
      const text = statisticsText(analysis, report)
      const artifact = await ctx.artifacts.create({
        name: `${safeFileBase(report.source)}-statistics.txt`,
        type: 'statistics',
        format: 'txt',
        mime: 'text/plain',
        bytes: new TextEncoder().encode(text),
        producer: 'report.export.statistics',
        parentArtifactId: typeof input.analysisArtifactId === 'string' ? input.analysisArtifactId : null,
        workflowRunId: ctx.runId,
        taskId: ctx.taskId,
        meta: { reportTitle: report.title, source: report.source },
      })
      return {
        ok: true,
        data: { statisticsArtifactId: artifact.id, statisticsName: artifact.name, statisticsSize: artifact.size },
        artifactIds: [artifact.id],
      }
    },
  }

  registry.register(generateOp)
  registry.register(exportPdfOp)
  registry.register(exportJsonOp)
  registry.register(exportStatisticsOp)
}

function safeFileBase(name: string): string {
  const base = name.replace(/\.(csv|json)$/i, '').replace(/[^\w.-]+/g, '_')
  return base || 'report'
}
