/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as AuthenticatedAiKiloCodeRouteImport } from './routes/_authenticated/ai/kilo-code'
import { Route as AuthenticatedAiOpencodeRouteImport } from './routes/_authenticated/ai/opencode'
import { Route as AuthenticatedAiPromptLibraryRouteImport } from './routes/_authenticated/ai/prompt-library'
import { Route as AuthenticatedAiProvidersRouteImport } from './routes/_authenticated/ai/providers'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedAutomationBrowserRouteImport } from './routes/_authenticated/automation/browser'
import { Route as AuthenticatedAutomationPdfRouteImport } from './routes/_authenticated/automation/pdf'
import { Route as AuthenticatedAutomationPptRouteImport } from './routes/_authenticated/automation/ppt'
import { Route as AuthenticatedAutomationTaskRunnerRouteImport } from './routes/_authenticated/automation/task-runner'
import { Route as AuthenticatedBigDealsIndexRouteImport } from './routes/_authenticated/big-deals/index'
import { Route as AuthenticatedBigDealsDealIdRouteImport } from './routes/_authenticated/big-deals/$dealId'
import { Route as AuthenticatedBusinessClientsRouteImport } from './routes/_authenticated/business/clients'
import { Route as AuthenticatedBusinessCrmRouteImport } from './routes/_authenticated/business/crm'
import { Route as AuthenticatedBusinessFinanceRouteImport } from './routes/_authenticated/business/finance'
import { Route as AuthenticatedBusinessInventoryRouteImport } from './routes/_authenticated/business/inventory'
import { Route as AuthenticatedBusinessMarketplaceRouteImport } from './routes/_authenticated/business/marketplace'
import { Route as AuthenticatedBusinessProjectsRouteImport } from './routes/_authenticated/business/projects'
import { Route as AuthenticatedBusinessReportingRouteImport } from './routes/_authenticated/business/reporting'
import { Route as AuthenticatedBusinessSalesRouteImport } from './routes/_authenticated/business/sales'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedGoogleIndexRouteImport } from './routes/_authenticated/google/index'
import { Route as AuthenticatedGoogleCalendarRouteImport } from './routes/_authenticated/google/calendar'
import { Route as AuthenticatedGoogleDocsRouteImport } from './routes/_authenticated/google/docs'
import { Route as AuthenticatedGoogleDriveRouteImport } from './routes/_authenticated/google/drive'
import { Route as AuthenticatedGoogleDriveFilePickerRouteImport } from './routes/_authenticated/google/drive-file-picker'
import { Route as AuthenticatedGoogleDrivePickerRouteImport } from './routes/_authenticated/google/drive-picker'
import { Route as AuthenticatedGoogleGmailRouteImport } from './routes/_authenticated/google/gmail'
import { Route as AuthenticatedGoogleSheetsRouteImport } from './routes/_authenticated/google/sheets'
import { Route as AuthenticatedGoogleSlidesRouteImport } from './routes/_authenticated/google/slides'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedProductivityDocumentsRouteImport } from './routes/_authenticated/productivity/documents'
import { Route as AuthenticatedProductivitySpreadsheetRouteImport } from './routes/_authenticated/productivity/spreadsheet'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSettingsAboutRouteImport } from './routes/_authenticated/settings/about'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedToolsIndexRouteImport } from './routes/_authenticated/tools/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedWorkspaceIndexRouteImport } from './routes/_authenticated/workspace/index'
import { Route as AuthenticatedWorkspaceAssistantRouteImport } from './routes/_authenticated/workspace/assistant'
import { Route as AuthenticatedWorkspaceHealthRouteImport } from './routes/_authenticated/workspace/health'
import { Route as AuthenticatedWorkspaceHistoryRouteImport } from './routes/_authenticated/workspace/history'
import { Route as AuthenticatedWorkspaceResourcesRouteImport } from './routes/_authenticated/workspace/resources'
import { Route as AuthenticatedWorkspaceRuntimeRouteImport } from './routes/_authenticated/workspace/runtime'
import { Route as AuthenticatedWorkspaceSdksRouteImport } from './routes/_authenticated/workspace/sdks'
import { Route as AuthenticatedWorkspaceSkillsRouteImport } from './routes/_authenticated/workspace/skills'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as AuthenticatedAiOpencodeIndexRouteImport } from './routes/_authenticated/ai/opencode/index'
import { Route as AuthenticatedAiOpencodeSettingsRouteImport } from './routes/_authenticated/ai/opencode/settings'
import { Route as AuthenticatedWorkspaceArtifactsIndexRouteImport } from './routes/_authenticated/workspace/artifacts/index'
import { Route as AuthenticatedWorkspaceArtifactsArtifactIdRouteImport } from './routes/_authenticated/workspace/artifacts/$artifactId'
import { Route as AuthenticatedWorkspaceHistoryEventIdRouteImport } from './routes/_authenticated/workspace/history/$eventId'
import { Route as AuthenticatedWorkspaceOperationsIndexRouteImport } from './routes/_authenticated/workspace/operations/index'
import { Route as AuthenticatedWorkspaceOperationsOperationIdRouteImport } from './routes/_authenticated/workspace/operations/$operationId'
import { Route as AuthenticatedWorkspaceTasksIndexRouteImport } from './routes/_authenticated/workspace/tasks/index'
import { Route as AuthenticatedWorkspaceTasksTaskIdRouteImport } from './routes/_authenticated/workspace/tasks/$taskId'
import { Route as AuthenticatedWorkspaceWorkflowsIndexRouteImport } from './routes/_authenticated/workspace/workflows/index'
import { Route as AuthenticatedWorkspaceWorkflowsWorkflowIdRouteImport } from './routes/_authenticated/workspace/workflows/$workflowId'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticatedAiKiloCodeRoute = AuthenticatedAiKiloCodeRouteImport.update({
  id: '/ai/kilo-code',
  path: '/ai/kilo-code',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiOpencodeRoute = AuthenticatedAiOpencodeRouteImport.update({
  id: '/ai/opencode',
  path: '/ai/opencode',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiPromptLibraryRoute =
  AuthenticatedAiPromptLibraryRouteImport.update({
    id: '/ai/prompt-library',
    path: '/ai/prompt-library',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiProvidersRoute =
  AuthenticatedAiProvidersRouteImport.update({
    id: '/ai/providers',
    path: '/ai/providers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutomationBrowserRoute =
  AuthenticatedAutomationBrowserRouteImport.update({
    id: '/automation/browser',
    path: '/automation/browser',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAutomationPdfRoute =
  AuthenticatedAutomationPdfRouteImport.update({
    id: '/automation/pdf',
    path: '/automation/pdf',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAutomationPptRoute =
  AuthenticatedAutomationPptRouteImport.update({
    id: '/automation/ppt',
    path: '/automation/ppt',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAutomationTaskRunnerRoute =
  AuthenticatedAutomationTaskRunnerRouteImport.update({
    id: '/automation/task-runner',
    path: '/automation/task-runner',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBigDealsIndexRoute =
  AuthenticatedBigDealsIndexRouteImport.update({
    id: '/big-deals/',
    path: '/big-deals/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBigDealsDealIdRoute =
  AuthenticatedBigDealsDealIdRouteImport.update({
    id: '/big-deals/$dealId',
    path: '/big-deals/$dealId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessClientsRoute =
  AuthenticatedBusinessClientsRouteImport.update({
    id: '/business/clients',
    path: '/business/clients',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessCrmRoute =
  AuthenticatedBusinessCrmRouteImport.update({
    id: '/business/crm',
    path: '/business/crm',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessFinanceRoute =
  AuthenticatedBusinessFinanceRouteImport.update({
    id: '/business/finance',
    path: '/business/finance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessInventoryRoute =
  AuthenticatedBusinessInventoryRouteImport.update({
    id: '/business/inventory',
    path: '/business/inventory',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessMarketplaceRoute =
  AuthenticatedBusinessMarketplaceRouteImport.update({
    id: '/business/marketplace',
    path: '/business/marketplace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessProjectsRoute =
  AuthenticatedBusinessProjectsRouteImport.update({
    id: '/business/projects',
    path: '/business/projects',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessReportingRoute =
  AuthenticatedBusinessReportingRouteImport.update({
    id: '/business/reporting',
    path: '/business/reporting',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBusinessSalesRoute =
  AuthenticatedBusinessSalesRouteImport.update({
    id: '/business/sales',
    path: '/business/sales',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGoogleIndexRoute =
  AuthenticatedGoogleIndexRouteImport.update({
    id: '/google/',
    path: '/google/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGoogleCalendarRoute =
  AuthenticatedGoogleCalendarRouteImport.update({
    id: '/google/calendar',
    path: '/google/calendar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGoogleDocsRoute = AuthenticatedGoogleDocsRouteImport.update({
  id: '/google/docs',
  path: '/google/docs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGoogleDriveRoute =
  AuthenticatedGoogleDriveRouteImport.update({
    id: '/google/drive',
    path: '/google/drive',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGoogleDriveFilePickerRoute =
  AuthenticatedGoogleDriveFilePickerRouteImport.update({
    id: '/google/drive-file-picker',
    path: '/google/drive-file-picker',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGoogleDrivePickerRoute =
  AuthenticatedGoogleDrivePickerRouteImport.update({
    id: '/google/drive-picker',
    path: '/google/drive-picker',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGoogleGmailRoute =
  AuthenticatedGoogleGmailRouteImport.update({
    id: '/google/gmail',
    path: '/google/gmail',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGoogleSheetsRoute =
  AuthenticatedGoogleSheetsRouteImport.update({
    id: '/google/sheets',
    path: '/google/sheets',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGoogleSlidesRoute =
  AuthenticatedGoogleSlidesRouteImport.update({
    id: '/google/slides',
    path: '/google/slides',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductivityDocumentsRoute =
  AuthenticatedProductivityDocumentsRouteImport.update({
    id: '/productivity/documents',
    path: '/productivity/documents',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductivitySpreadsheetRoute =
  AuthenticatedProductivitySpreadsheetRouteImport.update({
    id: '/productivity/spreadsheet',
    path: '/productivity/spreadsheet',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAboutRoute =
  AuthenticatedSettingsAboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedToolsIndexRoute = AuthenticatedToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkspaceIndexRoute =
  AuthenticatedWorkspaceIndexRouteImport.update({
    id: '/workspace/',
    path: '/workspace/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkspaceAssistantRoute =
  AuthenticatedWorkspaceAssistantRouteImport.update({
    id: '/workspace/assistant',
    path: '/workspace/assistant',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkspaceHealthRoute =
  AuthenticatedWorkspaceHealthRouteImport.update({
    id: '/workspace/health',
    path: '/workspace/health',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkspaceHistoryRoute =
  AuthenticatedWorkspaceHistoryRouteImport.update({
    id: '/workspace/history',
    path: '/workspace/history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkspaceResourcesRoute =
  AuthenticatedWorkspaceResourcesRouteImport.update({
    id: '/workspace/resources',
    path: '/workspace/resources',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkspaceRuntimeRoute =
  AuthenticatedWorkspaceRuntimeRouteImport.update({
    id: '/workspace/runtime',
    path: '/workspace/runtime',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkspaceSdksRoute =
  AuthenticatedWorkspaceSdksRouteImport.update({
    id: '/workspace/sdks',
    path: '/workspace/sdks',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkspaceSkillsRoute =
  AuthenticatedWorkspaceSkillsRouteImport.update({
    id: '/workspace/skills',
    path: '/workspace/skills',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiOpencodeIndexRoute =
  AuthenticatedAiOpencodeIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAiOpencodeRoute,
  } as any)
const AuthenticatedAiOpencodeSettingsRoute =
  AuthenticatedAiOpencodeSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAiOpencodeRoute,
  } as any)
const AuthenticatedWorkspaceArtifactsIndexRoute =
  AuthenticatedWorkspaceArtifactsIndexRouteImport.update({
    id: '/workspace/artifacts/',
    path: '/workspace/artifacts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkspaceArtifactsArtifactIdRoute =
  AuthenticatedWorkspaceArtifactsArtifactIdRouteImport.update({
    id: '/workspace/artifacts/$artifactId',
    path: '/workspace/artifacts/$artifactId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkspaceHistoryEventIdRoute =
  AuthenticatedWorkspaceHistoryEventIdRouteImport.update({
    id: '/$eventId',
    path: '/$eventId',
    getParentRoute: () => AuthenticatedWorkspaceHistoryRoute,
  } as any)
const AuthenticatedWorkspaceOperationsIndexRoute =
  AuthenticatedWorkspaceOperationsIndexRouteImport.update({
    id: '/workspace/operations/',
    path: '/workspace/operations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkspaceOperationsOperationIdRoute =
  AuthenticatedWorkspaceOperationsOperationIdRouteImport.update({
    id: '/workspace/operations/$operationId',
    path: '/workspace/operations/$operationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkspaceTasksIndexRoute =
  AuthenticatedWorkspaceTasksIndexRouteImport.update({
    id: '/workspace/tasks/',
    path: '/workspace/tasks/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkspaceTasksTaskIdRoute =
  AuthenticatedWorkspaceTasksTaskIdRouteImport.update({
    id: '/workspace/tasks/$taskId',
    path: '/workspace/tasks/$taskId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkspaceWorkflowsIndexRoute =
  AuthenticatedWorkspaceWorkflowsIndexRouteImport.update({
    id: '/workspace/workflows/',
    path: '/workspace/workflows/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkspaceWorkflowsWorkflowIdRoute =
  AuthenticatedWorkspaceWorkflowsWorkflowIdRouteImport.update({
    id: '/workspace/workflows/$workflowId',
    path: '/workspace/workflows/$workflowId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/clerk': typeof ClerkauthRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/history': typeof AuthenticatedHistoryRoute
  '/ai/kilo-code': typeof AuthenticatedAiKiloCodeRoute
  '/ai/opencode': typeof AuthenticatedAiOpencodeRouteWithChildren
  '/ai/prompt-library': typeof AuthenticatedAiPromptLibraryRoute
  '/ai/providers': typeof AuthenticatedAiProvidersRoute
  '/automation/browser': typeof AuthenticatedAutomationBrowserRoute
  '/automation/pdf': typeof AuthenticatedAutomationPdfRoute
  '/automation/ppt': typeof AuthenticatedAutomationPptRoute
  '/automation/task-runner': typeof AuthenticatedAutomationTaskRunnerRoute
  '/big-deals/$dealId': typeof AuthenticatedBigDealsDealIdRoute
  '/business/clients': typeof AuthenticatedBusinessClientsRoute
  '/business/crm': typeof AuthenticatedBusinessCrmRoute
  '/business/finance': typeof AuthenticatedBusinessFinanceRoute
  '/business/inventory': typeof AuthenticatedBusinessInventoryRoute
  '/business/marketplace': typeof AuthenticatedBusinessMarketplaceRoute
  '/business/projects': typeof AuthenticatedBusinessProjectsRoute
  '/business/reporting': typeof AuthenticatedBusinessReportingRoute
  '/business/sales': typeof AuthenticatedBusinessSalesRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/google/calendar': typeof AuthenticatedGoogleCalendarRoute
  '/google/docs': typeof AuthenticatedGoogleDocsRoute
  '/google/drive': typeof AuthenticatedGoogleDriveRoute
  '/google/drive-file-picker': typeof AuthenticatedGoogleDriveFilePickerRoute
  '/google/drive-picker': typeof AuthenticatedGoogleDrivePickerRoute
  '/google/gmail': typeof AuthenticatedGoogleGmailRoute
  '/google/sheets': typeof AuthenticatedGoogleSheetsRoute
  '/google/slides': typeof AuthenticatedGoogleSlidesRoute
  '/productivity/documents': typeof AuthenticatedProductivityDocumentsRoute
  '/productivity/spreadsheet': typeof AuthenticatedProductivitySpreadsheetRoute
  '/settings/about': typeof AuthenticatedSettingsAboutRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/workspace/assistant': typeof AuthenticatedWorkspaceAssistantRoute
  '/workspace/health': typeof AuthenticatedWorkspaceHealthRoute
  '/workspace/history': typeof AuthenticatedWorkspaceHistoryRouteWithChildren
  '/workspace/resources': typeof AuthenticatedWorkspaceResourcesRoute
  '/workspace/runtime': typeof AuthenticatedWorkspaceRuntimeRoute
  '/workspace/sdks': typeof AuthenticatedWorkspaceSdksRoute
  '/workspace/skills': typeof AuthenticatedWorkspaceSkillsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/apps/': typeof AuthenticatedAppsIndexRoute
  '/big-deals/': typeof AuthenticatedBigDealsIndexRoute
  '/chats/': typeof AuthenticatedChatsIndexRoute
  '/google/': typeof AuthenticatedGoogleIndexRoute
  '/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/tools/': typeof AuthenticatedToolsIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/workspace/': typeof AuthenticatedWorkspaceIndexRoute
  '/ai/opencode/settings': typeof AuthenticatedAiOpencodeSettingsRoute
  '/workspace/artifacts/$artifactId': typeof AuthenticatedWorkspaceArtifactsArtifactIdRoute
  '/workspace/history/$eventId': typeof AuthenticatedWorkspaceHistoryEventIdRoute
  '/workspace/operations/$operationId': typeof AuthenticatedWorkspaceOperationsOperationIdRoute
  '/workspace/tasks/$taskId': typeof AuthenticatedWorkspaceTasksTaskIdRoute
  '/workspace/workflows/$workflowId': typeof AuthenticatedWorkspaceWorkflowsWorkflowIdRoute
  '/ai/opencode/': typeof AuthenticatedAiOpencodeIndexRoute
  '/workspace/artifacts/': typeof AuthenticatedWorkspaceArtifactsIndexRoute
  '/workspace/operations/': typeof AuthenticatedWorkspaceOperationsIndexRoute
  '/workspace/tasks/': typeof AuthenticatedWorkspaceTasksIndexRoute
  '/workspace/workflows/': typeof AuthenticatedWorkspaceWorkflowsIndexRoute
}
export interface FileRoutesByTo {
  '/clerk': typeof ClerkauthRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/history': typeof AuthenticatedHistoryRoute
  '/': typeof AuthenticatedIndexRoute
  '/ai/kilo-code': typeof AuthenticatedAiKiloCodeRoute
  '/ai/prompt-library': typeof AuthenticatedAiPromptLibraryRoute
  '/ai/providers': typeof AuthenticatedAiProvidersRoute
  '/automation/browser': typeof AuthenticatedAutomationBrowserRoute
  '/automation/pdf': typeof AuthenticatedAutomationPdfRoute
  '/automation/ppt': typeof AuthenticatedAutomationPptRoute
  '/automation/task-runner': typeof AuthenticatedAutomationTaskRunnerRoute
  '/big-deals/$dealId': typeof AuthenticatedBigDealsDealIdRoute
  '/business/clients': typeof AuthenticatedBusinessClientsRoute
  '/business/crm': typeof AuthenticatedBusinessCrmRoute
  '/business/finance': typeof AuthenticatedBusinessFinanceRoute
  '/business/inventory': typeof AuthenticatedBusinessInventoryRoute
  '/business/marketplace': typeof AuthenticatedBusinessMarketplaceRoute
  '/business/projects': typeof AuthenticatedBusinessProjectsRoute
  '/business/reporting': typeof AuthenticatedBusinessReportingRoute
  '/business/sales': typeof AuthenticatedBusinessSalesRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/google/calendar': typeof AuthenticatedGoogleCalendarRoute
  '/google/docs': typeof AuthenticatedGoogleDocsRoute
  '/google/drive': typeof AuthenticatedGoogleDriveRoute
  '/google/drive-file-picker': typeof AuthenticatedGoogleDriveFilePickerRoute
  '/google/drive-picker': typeof AuthenticatedGoogleDrivePickerRoute
  '/google/gmail': typeof AuthenticatedGoogleGmailRoute
  '/google/sheets': typeof AuthenticatedGoogleSheetsRoute
  '/google/slides': typeof AuthenticatedGoogleSlidesRoute
  '/productivity/documents': typeof AuthenticatedProductivityDocumentsRoute
  '/productivity/spreadsheet': typeof AuthenticatedProductivitySpreadsheetRoute
  '/settings/about': typeof AuthenticatedSettingsAboutRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/workspace/assistant': typeof AuthenticatedWorkspaceAssistantRoute
  '/workspace/health': typeof AuthenticatedWorkspaceHealthRoute
  '/workspace/history': typeof AuthenticatedWorkspaceHistoryRouteWithChildren
  '/workspace/resources': typeof AuthenticatedWorkspaceResourcesRoute
  '/workspace/runtime': typeof AuthenticatedWorkspaceRuntimeRoute
  '/workspace/sdks': typeof AuthenticatedWorkspaceSdksRoute
  '/workspace/skills': typeof AuthenticatedWorkspaceSkillsRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/big-deals': typeof AuthenticatedBigDealsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/google': typeof AuthenticatedGoogleIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/tools': typeof AuthenticatedToolsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/workspace': typeof AuthenticatedWorkspaceIndexRoute
  '/ai/opencode/settings': typeof AuthenticatedAiOpencodeSettingsRoute
  '/workspace/artifacts/$artifactId': typeof AuthenticatedWorkspaceArtifactsArtifactIdRoute
  '/workspace/history/$eventId': typeof AuthenticatedWorkspaceHistoryEventIdRoute
  '/workspace/operations/$operationId': typeof AuthenticatedWorkspaceOperationsOperationIdRoute
  '/workspace/tasks/$taskId': typeof AuthenticatedWorkspaceTasksTaskIdRoute
  '/workspace/workflows/$workflowId': typeof AuthenticatedWorkspaceWorkflowsWorkflowIdRoute
  '/ai/opencode': typeof AuthenticatedAiOpencodeIndexRoute
  '/workspace/artifacts': typeof AuthenticatedWorkspaceArtifactsIndexRoute
  '/workspace/operations': typeof AuthenticatedWorkspaceOperationsIndexRoute
  '/workspace/tasks': typeof AuthenticatedWorkspaceTasksIndexRoute
  '/workspace/workflows': typeof AuthenticatedWorkspaceWorkflowsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/ai/kilo-code': typeof AuthenticatedAiKiloCodeRoute
  '/_authenticated/ai/opencode': typeof AuthenticatedAiOpencodeRouteWithChildren
  '/_authenticated/ai/prompt-library': typeof AuthenticatedAiPromptLibraryRoute
  '/_authenticated/ai/providers': typeof AuthenticatedAiProvidersRoute
  '/_authenticated/automation/browser': typeof AuthenticatedAutomationBrowserRoute
  '/_authenticated/automation/pdf': typeof AuthenticatedAutomationPdfRoute
  '/_authenticated/automation/ppt': typeof AuthenticatedAutomationPptRoute
  '/_authenticated/automation/task-runner': typeof AuthenticatedAutomationTaskRunnerRoute
  '/_authenticated/big-deals/$dealId': typeof AuthenticatedBigDealsDealIdRoute
  '/_authenticated/business/clients': typeof AuthenticatedBusinessClientsRoute
  '/_authenticated/business/crm': typeof AuthenticatedBusinessCrmRoute
  '/_authenticated/business/finance': typeof AuthenticatedBusinessFinanceRoute
  '/_authenticated/business/inventory': typeof AuthenticatedBusinessInventoryRoute
  '/_authenticated/business/marketplace': typeof AuthenticatedBusinessMarketplaceRoute
  '/_authenticated/business/projects': typeof AuthenticatedBusinessProjectsRoute
  '/_authenticated/business/reporting': typeof AuthenticatedBusinessReportingRoute
  '/_authenticated/business/sales': typeof AuthenticatedBusinessSalesRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/google/calendar': typeof AuthenticatedGoogleCalendarRoute
  '/_authenticated/google/docs': typeof AuthenticatedGoogleDocsRoute
  '/_authenticated/google/drive': typeof AuthenticatedGoogleDriveRoute
  '/_authenticated/google/drive-file-picker': typeof AuthenticatedGoogleDriveFilePickerRoute
  '/_authenticated/google/drive-picker': typeof AuthenticatedGoogleDrivePickerRoute
  '/_authenticated/google/gmail': typeof AuthenticatedGoogleGmailRoute
  '/_authenticated/google/sheets': typeof AuthenticatedGoogleSheetsRoute
  '/_authenticated/google/slides': typeof AuthenticatedGoogleSlidesRoute
  '/_authenticated/productivity/documents': typeof AuthenticatedProductivityDocumentsRoute
  '/_authenticated/productivity/spreadsheet': typeof AuthenticatedProductivitySpreadsheetRoute
  '/_authenticated/settings/about': typeof AuthenticatedSettingsAboutRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/workspace/assistant': typeof AuthenticatedWorkspaceAssistantRoute
  '/_authenticated/workspace/health': typeof AuthenticatedWorkspaceHealthRoute
  '/_authenticated/workspace/history': typeof AuthenticatedWorkspaceHistoryRouteWithChildren
  '/_authenticated/workspace/resources': typeof AuthenticatedWorkspaceResourcesRoute
  '/_authenticated/workspace/runtime': typeof AuthenticatedWorkspaceRuntimeRoute
  '/_authenticated/workspace/sdks': typeof AuthenticatedWorkspaceSdksRoute
  '/_authenticated/workspace/skills': typeof AuthenticatedWorkspaceSkillsRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/big-deals/': typeof AuthenticatedBigDealsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/google/': typeof AuthenticatedGoogleIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/tools/': typeof AuthenticatedToolsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/workspace/': typeof AuthenticatedWorkspaceIndexRoute
  '/_authenticated/ai/opencode/settings': typeof AuthenticatedAiOpencodeSettingsRoute
  '/_authenticated/workspace/artifacts/$artifactId': typeof AuthenticatedWorkspaceArtifactsArtifactIdRoute
  '/_authenticated/workspace/history/$eventId': typeof AuthenticatedWorkspaceHistoryEventIdRoute
  '/_authenticated/workspace/operations/$operationId': typeof AuthenticatedWorkspaceOperationsOperationIdRoute
  '/_authenticated/workspace/tasks/$taskId': typeof AuthenticatedWorkspaceTasksTaskIdRoute
  '/_authenticated/workspace/workflows/$workflowId': typeof AuthenticatedWorkspaceWorkflowsWorkflowIdRoute
  '/_authenticated/ai/opencode/': typeof AuthenticatedAiOpencodeIndexRoute
  '/_authenticated/workspace/artifacts/': typeof AuthenticatedWorkspaceArtifactsIndexRoute
  '/_authenticated/workspace/operations/': typeof AuthenticatedWorkspaceOperationsIndexRoute
  '/_authenticated/workspace/tasks/': typeof AuthenticatedWorkspaceTasksIndexRoute
  '/_authenticated/workspace/workflows/': typeof AuthenticatedWorkspaceWorkflowsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clerk'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/history'
    | '/ai/kilo-code'
    | '/ai/opencode'
    | '/ai/prompt-library'
    | '/ai/providers'
    | '/automation/browser'
    | '/automation/pdf'
    | '/automation/ppt'
    | '/automation/task-runner'
    | '/big-deals/$dealId'
    | '/business/clients'
    | '/business/crm'
    | '/business/finance'
    | '/business/inventory'
    | '/business/marketplace'
    | '/business/projects'
    | '/business/reporting'
    | '/business/sales'
    | '/errors/$error'
    | '/google/calendar'
    | '/google/docs'
    | '/google/drive'
    | '/google/drive-file-picker'
    | '/google/drive-picker'
    | '/google/gmail'
    | '/google/sheets'
    | '/google/slides'
    | '/productivity/documents'
    | '/productivity/spreadsheet'
    | '/settings/about'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/workspace/assistant'
    | '/workspace/health'
    | '/workspace/history'
    | '/workspace/resources'
    | '/workspace/runtime'
    | '/workspace/sdks'
    | '/workspace/skills'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/apps/'
    | '/big-deals/'
    | '/chats/'
    | '/google/'
    | '/help-center/'
    | '/settings/'
    | '/tasks/'
    | '/tools/'
    | '/users/'
    | '/workspace/'
    | '/ai/opencode/settings'
    | '/workspace/artifacts/$artifactId'
    | '/workspace/history/$eventId'
    | '/workspace/operations/$operationId'
    | '/workspace/tasks/$taskId'
    | '/workspace/workflows/$workflowId'
    | '/ai/opencode/'
    | '/workspace/artifacts/'
    | '/workspace/operations/'
    | '/workspace/tasks/'
    | '/workspace/workflows/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clerk'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/history'
    | '/'
    | '/ai/kilo-code'
    | '/ai/prompt-library'
    | '/ai/providers'
    | '/automation/browser'
    | '/automation/pdf'
    | '/automation/ppt'
    | '/automation/task-runner'
    | '/big-deals/$dealId'
    | '/business/clients'
    | '/business/crm'
    | '/business/finance'
    | '/business/inventory'
    | '/business/marketplace'
    | '/business/projects'
    | '/business/reporting'
    | '/business/sales'
    | '/errors/$error'
    | '/google/calendar'
    | '/google/docs'
    | '/google/drive'
    | '/google/drive-file-picker'
    | '/google/drive-picker'
    | '/google/gmail'
    | '/google/sheets'
    | '/google/slides'
    | '/productivity/documents'
    | '/productivity/spreadsheet'
    | '/settings/about'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/workspace/assistant'
    | '/workspace/health'
    | '/workspace/history'
    | '/workspace/resources'
    | '/workspace/runtime'
    | '/workspace/sdks'
    | '/workspace/skills'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/apps'
    | '/big-deals'
    | '/chats'
    | '/google'
    | '/help-center'
    | '/settings'
    | '/tasks'
    | '/tools'
    | '/users'
    | '/workspace'
    | '/ai/opencode/settings'
    | '/workspace/artifacts/$artifactId'
    | '/workspace/history/$eventId'
    | '/workspace/operations/$operationId'
    | '/workspace/tasks/$taskId'
    | '/workspace/workflows/$workflowId'
    | '/ai/opencode'
    | '/workspace/artifacts'
    | '/workspace/operations'
    | '/workspace/tasks'
    | '/workspace/workflows'
  id:
    | '__root__'
    | '/_authenticated'
    | '/clerk'
    | '/_authenticated/settings'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/history'
    | '/_authenticated/'
    | '/_authenticated/ai/kilo-code'
    | '/_authenticated/ai/opencode'
    | '/_authenticated/ai/prompt-library'
    | '/_authenticated/ai/providers'
    | '/_authenticated/automation/browser'
    | '/_authenticated/automation/pdf'
    | '/_authenticated/automation/ppt'
    | '/_authenticated/automation/task-runner'
    | '/_authenticated/big-deals/$dealId'
    | '/_authenticated/business/clients'
    | '/_authenticated/business/crm'
    | '/_authenticated/business/finance'
    | '/_authenticated/business/inventory'
    | '/_authenticated/business/marketplace'
    | '/_authenticated/business/projects'
    | '/_authenticated/business/reporting'
    | '/_authenticated/business/sales'
    | '/_authenticated/errors/$error'
    | '/_authenticated/google/calendar'
    | '/_authenticated/google/docs'
    | '/_authenticated/google/drive'
    | '/_authenticated/google/drive-file-picker'
    | '/_authenticated/google/drive-picker'
    | '/_authenticated/google/gmail'
    | '/_authenticated/google/sheets'
    | '/_authenticated/google/slides'
    | '/_authenticated/productivity/documents'
    | '/_authenticated/productivity/spreadsheet'
    | '/_authenticated/settings/about'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/workspace/assistant'
    | '/_authenticated/workspace/health'
    | '/_authenticated/workspace/history'
    | '/_authenticated/workspace/resources'
    | '/_authenticated/workspace/runtime'
    | '/_authenticated/workspace/sdks'
    | '/_authenticated/workspace/skills'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/_authenticated/apps/'
    | '/_authenticated/big-deals/'
    | '/_authenticated/chats/'
    | '/_authenticated/google/'
    | '/_authenticated/help-center/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/tools/'
    | '/_authenticated/users/'
    | '/_authenticated/workspace/'
    | '/_authenticated/ai/opencode/settings'
    | '/_authenticated/workspace/artifacts/$artifactId'
    | '/_authenticated/workspace/history/$eventId'
    | '/_authenticated/workspace/operations/$operationId'
    | '/_authenticated/workspace/tasks/$taskId'
    | '/_authenticated/workspace/workflows/$workflowId'
    | '/_authenticated/ai/opencode/'
    | '/_authenticated/workspace/artifacts/'
    | '/_authenticated/workspace/operations/'
    | '/_authenticated/workspace/tasks/'
    | '/_authenticated/workspace/workflows/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/ai/kilo-code': {
      id: '/_authenticated/ai/kilo-code'
      path: '/ai/kilo-code'
      fullPath: '/ai/kilo-code'
      preLoaderRoute: typeof AuthenticatedAiKiloCodeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai/opencode': {
      id: '/_authenticated/ai/opencode'
      path: '/ai/opencode'
      fullPath: '/ai/opencode'
      preLoaderRoute: typeof AuthenticatedAiOpencodeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai/prompt-library': {
      id: '/_authenticated/ai/prompt-library'
      path: '/ai/prompt-library'
      fullPath: '/ai/prompt-library'
      preLoaderRoute: typeof AuthenticatedAiPromptLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai/providers': {
      id: '/_authenticated/ai/providers'
      path: '/ai/providers'
      fullPath: '/ai/providers'
      preLoaderRoute: typeof AuthenticatedAiProvidersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automation/browser': {
      id: '/_authenticated/automation/browser'
      path: '/automation/browser'
      fullPath: '/automation/browser'
      preLoaderRoute: typeof AuthenticatedAutomationBrowserRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automation/pdf': {
      id: '/_authenticated/automation/pdf'
      path: '/automation/pdf'
      fullPath: '/automation/pdf'
      preLoaderRoute: typeof AuthenticatedAutomationPdfRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automation/ppt': {
      id: '/_authenticated/automation/ppt'
      path: '/automation/ppt'
      fullPath: '/automation/ppt'
      preLoaderRoute: typeof AuthenticatedAutomationPptRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automation/task-runner': {
      id: '/_authenticated/automation/task-runner'
      path: '/automation/task-runner'
      fullPath: '/automation/task-runner'
      preLoaderRoute: typeof AuthenticatedAutomationTaskRunnerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/big-deals/': {
      id: '/_authenticated/big-deals/'
      path: '/big-deals'
      fullPath: '/big-deals/'
      preLoaderRoute: typeof AuthenticatedBigDealsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/big-deals/$dealId': {
      id: '/_authenticated/big-deals/$dealId'
      path: '/big-deals/$dealId'
      fullPath: '/big-deals/$dealId'
      preLoaderRoute: typeof AuthenticatedBigDealsDealIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business/clients': {
      id: '/_authenticated/business/clients'
      path: '/business/clients'
      fullPath: '/business/clients'
      preLoaderRoute: typeof AuthenticatedBusinessClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business/crm': {
      id: '/_authenticated/business/crm'
      path: '/business/crm'
      fullPath: '/business/crm'
      preLoaderRoute: typeof AuthenticatedBusinessCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business/finance': {
      id: '/_authenticated/business/finance'
      path: '/business/finance'
      fullPath: '/business/finance'
      preLoaderRoute: typeof AuthenticatedBusinessFinanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business/inventory': {
      id: '/_authenticated/business/inventory'
      path: '/business/inventory'
      fullPath: '/business/inventory'
      preLoaderRoute: typeof AuthenticatedBusinessInventoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business/marketplace': {
      id: '/_authenticated/business/marketplace'
      path: '/business/marketplace'
      fullPath: '/business/marketplace'
      preLoaderRoute: typeof AuthenticatedBusinessMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business/projects': {
      id: '/_authenticated/business/projects'
      path: '/business/projects'
      fullPath: '/business/projects'
      preLoaderRoute: typeof AuthenticatedBusinessProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business/reporting': {
      id: '/_authenticated/business/reporting'
      path: '/business/reporting'
      fullPath: '/business/reporting'
      preLoaderRoute: typeof AuthenticatedBusinessReportingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/business/sales': {
      id: '/_authenticated/business/sales'
      path: '/business/sales'
      fullPath: '/business/sales'
      preLoaderRoute: typeof AuthenticatedBusinessSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/google/': {
      id: '/_authenticated/google/'
      path: '/google'
      fullPath: '/google/'
      preLoaderRoute: typeof AuthenticatedGoogleIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/google/calendar': {
      id: '/_authenticated/google/calendar'
      path: '/google/calendar'
      fullPath: '/google/calendar'
      preLoaderRoute: typeof AuthenticatedGoogleCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/google/docs': {
      id: '/_authenticated/google/docs'
      path: '/google/docs'
      fullPath: '/google/docs'
      preLoaderRoute: typeof AuthenticatedGoogleDocsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/google/drive': {
      id: '/_authenticated/google/drive'
      path: '/google/drive'
      fullPath: '/google/drive'
      preLoaderRoute: typeof AuthenticatedGoogleDriveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/google/drive-file-picker': {
      id: '/_authenticated/google/drive-file-picker'
      path: '/google/drive-file-picker'
      fullPath: '/google/drive-file-picker'
      preLoaderRoute: typeof AuthenticatedGoogleDriveFilePickerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/google/drive-picker': {
      id: '/_authenticated/google/drive-picker'
      path: '/google/drive-picker'
      fullPath: '/google/drive-picker'
      preLoaderRoute: typeof AuthenticatedGoogleDrivePickerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/google/gmail': {
      id: '/_authenticated/google/gmail'
      path: '/google/gmail'
      fullPath: '/google/gmail'
      preLoaderRoute: typeof AuthenticatedGoogleGmailRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/google/sheets': {
      id: '/_authenticated/google/sheets'
      path: '/google/sheets'
      fullPath: '/google/sheets'
      preLoaderRoute: typeof AuthenticatedGoogleSheetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/google/slides': {
      id: '/_authenticated/google/slides'
      path: '/google/slides'
      fullPath: '/google/slides'
      preLoaderRoute: typeof AuthenticatedGoogleSlidesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/productivity/documents': {
      id: '/_authenticated/productivity/documents'
      path: '/productivity/documents'
      fullPath: '/productivity/documents'
      preLoaderRoute: typeof AuthenticatedProductivityDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/productivity/spreadsheet': {
      id: '/_authenticated/productivity/spreadsheet'
      path: '/productivity/spreadsheet'
      fullPath: '/productivity/spreadsheet'
      preLoaderRoute: typeof AuthenticatedProductivitySpreadsheetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/about': {
      id: '/_authenticated/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof AuthenticatedSettingsAboutRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools/': {
      id: '/_authenticated/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof AuthenticatedToolsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspace/': {
      id: '/_authenticated/workspace/'
      path: '/workspace'
      fullPath: '/workspace/'
      preLoaderRoute: typeof AuthenticatedWorkspaceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspace/assistant': {
      id: '/_authenticated/workspace/assistant'
      path: '/workspace/assistant'
      fullPath: '/workspace/assistant'
      preLoaderRoute: typeof AuthenticatedWorkspaceAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspace/health': {
      id: '/_authenticated/workspace/health'
      path: '/workspace/health'
      fullPath: '/workspace/health'
      preLoaderRoute: typeof AuthenticatedWorkspaceHealthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspace/history': {
      id: '/_authenticated/workspace/history'
      path: '/workspace/history'
      fullPath: '/workspace/history'
      preLoaderRoute: typeof AuthenticatedWorkspaceHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspace/resources': {
      id: '/_authenticated/workspace/resources'
      path: '/workspace/resources'
      fullPath: '/workspace/resources'
      preLoaderRoute: typeof AuthenticatedWorkspaceResourcesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspace/runtime': {
      id: '/_authenticated/workspace/runtime'
      path: '/workspace/runtime'
      fullPath: '/workspace/runtime'
      preLoaderRoute: typeof AuthenticatedWorkspaceRuntimeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspace/sdks': {
      id: '/_authenticated/workspace/sdks'
      path: '/workspace/sdks'
      fullPath: '/workspace/sdks'
      preLoaderRoute: typeof AuthenticatedWorkspaceSdksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspace/skills': {
      id: '/_authenticated/workspace/skills'
      path: '/workspace/skills'
      fullPath: '/workspace/skills'
      preLoaderRoute: typeof AuthenticatedWorkspaceSkillsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/_authenticated/ai/opencode/': {
      id: '/_authenticated/ai/opencode/'
      path: '/'
      fullPath: '/ai/opencode/'
      preLoaderRoute: typeof AuthenticatedAiOpencodeIndexRouteImport
      parentRoute: typeof AuthenticatedAiOpencodeRoute
    }
    '/_authenticated/ai/opencode/settings': {
      id: '/_authenticated/ai/opencode/settings'
      path: '/settings'
      fullPath: '/ai/opencode/settings'
      preLoaderRoute: typeof AuthenticatedAiOpencodeSettingsRouteImport
      parentRoute: typeof AuthenticatedAiOpencodeRoute
    }
    '/_authenticated/workspace/artifacts/': {
      id: '/_authenticated/workspace/artifacts/'
      path: '/workspace/artifacts'
      fullPath: '/workspace/artifacts/'
      preLoaderRoute: typeof AuthenticatedWorkspaceArtifactsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspace/artifacts/$artifactId': {
      id: '/_authenticated/workspace/artifacts/$artifactId'
      path: '/workspace/artifacts/$artifactId'
      fullPath: '/workspace/artifacts/$artifactId'
      preLoaderRoute: typeof AuthenticatedWorkspaceArtifactsArtifactIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspace/history/$eventId': {
      id: '/_authenticated/workspace/history/$eventId'
      path: '/$eventId'
      fullPath: '/workspace/history/$eventId'
      preLoaderRoute: typeof AuthenticatedWorkspaceHistoryEventIdRouteImport
      parentRoute: typeof AuthenticatedWorkspaceHistoryRoute
    }
    '/_authenticated/workspace/operations/': {
      id: '/_authenticated/workspace/operations/'
      path: '/workspace/operations'
      fullPath: '/workspace/operations/'
      preLoaderRoute: typeof AuthenticatedWorkspaceOperationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspace/operations/$operationId': {
      id: '/_authenticated/workspace/operations/$operationId'
      path: '/workspace/operations/$operationId'
      fullPath: '/workspace/operations/$operationId'
      preLoaderRoute: typeof AuthenticatedWorkspaceOperationsOperationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspace/tasks/': {
      id: '/_authenticated/workspace/tasks/'
      path: '/workspace/tasks'
      fullPath: '/workspace/tasks/'
      preLoaderRoute: typeof AuthenticatedWorkspaceTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspace/tasks/$taskId': {
      id: '/_authenticated/workspace/tasks/$taskId'
      path: '/workspace/tasks/$taskId'
      fullPath: '/workspace/tasks/$taskId'
      preLoaderRoute: typeof AuthenticatedWorkspaceTasksTaskIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspace/workflows/': {
      id: '/_authenticated/workspace/workflows/'
      path: '/workspace/workflows'
      fullPath: '/workspace/workflows/'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkflowsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workspace/workflows/$workflowId': {
      id: '/_authenticated/workspace/workflows/$workflowId'
      path: '/workspace/workflows/$workflowId'
      fullPath: '/workspace/workflows/$workflowId'
      preLoaderRoute: typeof AuthenticatedWorkspaceWorkflowsWorkflowIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAboutRoute: typeof AuthenticatedSettingsAboutRoute
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAboutRoute: AuthenticatedSettingsAboutRoute,
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedAiOpencodeRouteChildren {
  AuthenticatedAiOpencodeSettingsRoute: typeof AuthenticatedAiOpencodeSettingsRoute
  AuthenticatedAiOpencodeIndexRoute: typeof AuthenticatedAiOpencodeIndexRoute
}

const AuthenticatedAiOpencodeRouteChildren: AuthenticatedAiOpencodeRouteChildren =
  {
    AuthenticatedAiOpencodeSettingsRoute: AuthenticatedAiOpencodeSettingsRoute,
    AuthenticatedAiOpencodeIndexRoute: AuthenticatedAiOpencodeIndexRoute,
  }

const AuthenticatedAiOpencodeRouteWithChildren =
  AuthenticatedAiOpencodeRoute._addFileChildren(
    AuthenticatedAiOpencodeRouteChildren,
  )

interface AuthenticatedWorkspaceHistoryRouteChildren {
  AuthenticatedWorkspaceHistoryEventIdRoute: typeof AuthenticatedWorkspaceHistoryEventIdRoute
}

const AuthenticatedWorkspaceHistoryRouteChildren: AuthenticatedWorkspaceHistoryRouteChildren =
  {
    AuthenticatedWorkspaceHistoryEventIdRoute:
      AuthenticatedWorkspaceHistoryEventIdRoute,
  }

const AuthenticatedWorkspaceHistoryRouteWithChildren =
  AuthenticatedWorkspaceHistoryRoute._addFileChildren(
    AuthenticatedWorkspaceHistoryRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAiKiloCodeRoute: typeof AuthenticatedAiKiloCodeRoute
  AuthenticatedAiOpencodeRoute: typeof AuthenticatedAiOpencodeRouteWithChildren
  AuthenticatedAiPromptLibraryRoute: typeof AuthenticatedAiPromptLibraryRoute
  AuthenticatedAiProvidersRoute: typeof AuthenticatedAiProvidersRoute
  AuthenticatedAutomationBrowserRoute: typeof AuthenticatedAutomationBrowserRoute
  AuthenticatedAutomationPdfRoute: typeof AuthenticatedAutomationPdfRoute
  AuthenticatedAutomationPptRoute: typeof AuthenticatedAutomationPptRoute
  AuthenticatedAutomationTaskRunnerRoute: typeof AuthenticatedAutomationTaskRunnerRoute
  AuthenticatedBigDealsDealIdRoute: typeof AuthenticatedBigDealsDealIdRoute
  AuthenticatedBusinessClientsRoute: typeof AuthenticatedBusinessClientsRoute
  AuthenticatedBusinessCrmRoute: typeof AuthenticatedBusinessCrmRoute
  AuthenticatedBusinessFinanceRoute: typeof AuthenticatedBusinessFinanceRoute
  AuthenticatedBusinessInventoryRoute: typeof AuthenticatedBusinessInventoryRoute
  AuthenticatedBusinessMarketplaceRoute: typeof AuthenticatedBusinessMarketplaceRoute
  AuthenticatedBusinessProjectsRoute: typeof AuthenticatedBusinessProjectsRoute
  AuthenticatedBusinessReportingRoute: typeof AuthenticatedBusinessReportingRoute
  AuthenticatedBusinessSalesRoute: typeof AuthenticatedBusinessSalesRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedGoogleCalendarRoute: typeof AuthenticatedGoogleCalendarRoute
  AuthenticatedGoogleDocsRoute: typeof AuthenticatedGoogleDocsRoute
  AuthenticatedGoogleDriveRoute: typeof AuthenticatedGoogleDriveRoute
  AuthenticatedGoogleDriveFilePickerRoute: typeof AuthenticatedGoogleDriveFilePickerRoute
  AuthenticatedGoogleDrivePickerRoute: typeof AuthenticatedGoogleDrivePickerRoute
  AuthenticatedGoogleGmailRoute: typeof AuthenticatedGoogleGmailRoute
  AuthenticatedGoogleSheetsRoute: typeof AuthenticatedGoogleSheetsRoute
  AuthenticatedGoogleSlidesRoute: typeof AuthenticatedGoogleSlidesRoute
  AuthenticatedProductivityDocumentsRoute: typeof AuthenticatedProductivityDocumentsRoute
  AuthenticatedProductivitySpreadsheetRoute: typeof AuthenticatedProductivitySpreadsheetRoute
  AuthenticatedWorkspaceAssistantRoute: typeof AuthenticatedWorkspaceAssistantRoute
  AuthenticatedWorkspaceHealthRoute: typeof AuthenticatedWorkspaceHealthRoute
  AuthenticatedWorkspaceHistoryRoute: typeof AuthenticatedWorkspaceHistoryRouteWithChildren
  AuthenticatedWorkspaceResourcesRoute: typeof AuthenticatedWorkspaceResourcesRoute
  AuthenticatedWorkspaceRuntimeRoute: typeof AuthenticatedWorkspaceRuntimeRoute
  AuthenticatedWorkspaceSdksRoute: typeof AuthenticatedWorkspaceSdksRoute
  AuthenticatedWorkspaceSkillsRoute: typeof AuthenticatedWorkspaceSkillsRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedBigDealsIndexRoute: typeof AuthenticatedBigDealsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedGoogleIndexRoute: typeof AuthenticatedGoogleIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedToolsIndexRoute: typeof AuthenticatedToolsIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedWorkspaceIndexRoute: typeof AuthenticatedWorkspaceIndexRoute
  AuthenticatedWorkspaceArtifactsArtifactIdRoute: typeof AuthenticatedWorkspaceArtifactsArtifactIdRoute
  AuthenticatedWorkspaceOperationsOperationIdRoute: typeof AuthenticatedWorkspaceOperationsOperationIdRoute
  AuthenticatedWorkspaceTasksTaskIdRoute: typeof AuthenticatedWorkspaceTasksTaskIdRoute
  AuthenticatedWorkspaceWorkflowsWorkflowIdRoute: typeof AuthenticatedWorkspaceWorkflowsWorkflowIdRoute
  AuthenticatedWorkspaceArtifactsIndexRoute: typeof AuthenticatedWorkspaceArtifactsIndexRoute
  AuthenticatedWorkspaceOperationsIndexRoute: typeof AuthenticatedWorkspaceOperationsIndexRoute
  AuthenticatedWorkspaceTasksIndexRoute: typeof AuthenticatedWorkspaceTasksIndexRoute
  AuthenticatedWorkspaceWorkflowsIndexRoute: typeof AuthenticatedWorkspaceWorkflowsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAiKiloCodeRoute: AuthenticatedAiKiloCodeRoute,
  AuthenticatedAiOpencodeRoute: AuthenticatedAiOpencodeRouteWithChildren,
  AuthenticatedAiPromptLibraryRoute: AuthenticatedAiPromptLibraryRoute,
  AuthenticatedAiProvidersRoute: AuthenticatedAiProvidersRoute,
  AuthenticatedAutomationBrowserRoute: AuthenticatedAutomationBrowserRoute,
  AuthenticatedAutomationPdfRoute: AuthenticatedAutomationPdfRoute,
  AuthenticatedAutomationPptRoute: AuthenticatedAutomationPptRoute,
  AuthenticatedAutomationTaskRunnerRoute:
    AuthenticatedAutomationTaskRunnerRoute,
  AuthenticatedBigDealsDealIdRoute: AuthenticatedBigDealsDealIdRoute,
  AuthenticatedBusinessClientsRoute: AuthenticatedBusinessClientsRoute,
  AuthenticatedBusinessCrmRoute: AuthenticatedBusinessCrmRoute,
  AuthenticatedBusinessFinanceRoute: AuthenticatedBusinessFinanceRoute,
  AuthenticatedBusinessInventoryRoute: AuthenticatedBusinessInventoryRoute,
  AuthenticatedBusinessMarketplaceRoute: AuthenticatedBusinessMarketplaceRoute,
  AuthenticatedBusinessProjectsRoute: AuthenticatedBusinessProjectsRoute,
  AuthenticatedBusinessReportingRoute: AuthenticatedBusinessReportingRoute,
  AuthenticatedBusinessSalesRoute: AuthenticatedBusinessSalesRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedGoogleCalendarRoute: AuthenticatedGoogleCalendarRoute,
  AuthenticatedGoogleDocsRoute: AuthenticatedGoogleDocsRoute,
  AuthenticatedGoogleDriveRoute: AuthenticatedGoogleDriveRoute,
  AuthenticatedGoogleDriveFilePickerRoute:
    AuthenticatedGoogleDriveFilePickerRoute,
  AuthenticatedGoogleDrivePickerRoute: AuthenticatedGoogleDrivePickerRoute,
  AuthenticatedGoogleGmailRoute: AuthenticatedGoogleGmailRoute,
  AuthenticatedGoogleSheetsRoute: AuthenticatedGoogleSheetsRoute,
  AuthenticatedGoogleSlidesRoute: AuthenticatedGoogleSlidesRoute,
  AuthenticatedProductivityDocumentsRoute:
    AuthenticatedProductivityDocumentsRoute,
  AuthenticatedProductivitySpreadsheetRoute:
    AuthenticatedProductivitySpreadsheetRoute,
  AuthenticatedWorkspaceAssistantRoute: AuthenticatedWorkspaceAssistantRoute,
  AuthenticatedWorkspaceHealthRoute: AuthenticatedWorkspaceHealthRoute,
  AuthenticatedWorkspaceHistoryRoute:
    AuthenticatedWorkspaceHistoryRouteWithChildren,
  AuthenticatedWorkspaceResourcesRoute: AuthenticatedWorkspaceResourcesRoute,
  AuthenticatedWorkspaceRuntimeRoute: AuthenticatedWorkspaceRuntimeRoute,
  AuthenticatedWorkspaceSdksRoute: AuthenticatedWorkspaceSdksRoute,
  AuthenticatedWorkspaceSkillsRoute: AuthenticatedWorkspaceSkillsRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedBigDealsIndexRoute: AuthenticatedBigDealsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedGoogleIndexRoute: AuthenticatedGoogleIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedToolsIndexRoute: AuthenticatedToolsIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedWorkspaceIndexRoute: AuthenticatedWorkspaceIndexRoute,
  AuthenticatedWorkspaceArtifactsArtifactIdRoute:
    AuthenticatedWorkspaceArtifactsArtifactIdRoute,
  AuthenticatedWorkspaceOperationsOperationIdRoute:
    AuthenticatedWorkspaceOperationsOperationIdRoute,
  AuthenticatedWorkspaceTasksTaskIdRoute:
    AuthenticatedWorkspaceTasksTaskIdRoute,
  AuthenticatedWorkspaceWorkflowsWorkflowIdRoute:
    AuthenticatedWorkspaceWorkflowsWorkflowIdRoute,
  AuthenticatedWorkspaceArtifactsIndexRoute:
    AuthenticatedWorkspaceArtifactsIndexRoute,
  AuthenticatedWorkspaceOperationsIndexRoute:
    AuthenticatedWorkspaceOperationsIndexRoute,
  AuthenticatedWorkspaceTasksIndexRoute: AuthenticatedWorkspaceTasksIndexRoute,
  AuthenticatedWorkspaceWorkflowsIndexRoute:
    AuthenticatedWorkspaceWorkflowsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
